#!/bin/bash
echo Este script sirve para cambiar el nombre del equipo.
read nombre
echo Se esta cambiando el nombre al equipo por $nombre
echo $nombre > /etc/hostname
read hostname $nombre
echo Comprobamos que el nombre se ha cambiado
cat /etc/hostname
